---
title: "Ames EDA_MichelleBui"
author: "Michelle Bui"
date: "17/05/2022"
output: html_document
---

```{r  Loading Packages}
library(tidyverse)
library(ggridges)
library(viridis)
library(hrbrthemes)
library(ggmap)
library(ggExtra)
library(RColorBrewer)
library(ggthemes)
```

```{r loading files, merging datasets}
getwd()
house_price <- data.frame(read.csv('data/Ames_HousePrice.csv'))
house_price
house_price <-  house_price[!house_price$'PID'==908154205, ]

```

```{r  Full Model - which variables are initially significant?}
house_price
full_mod <- lm(SalePrice ~ ., data = house_price)
summary(full_mod)
```

```{r  Exploring NA values }
sum(is.na(house_price))  #615 NA values 
house_price[rowSums(is.na(house_price)) > 0, ]

```

```{r  What does the distribution of Sale Price look like?}

house_price$SalePriceShort <- round(house_price$SalePrice/1000,2)
house_price$SalePriceShort

house_price %>% ggplot(aes(x = SalePriceShort)) + 
  geom_histogram(aes(y=..density..), bins = 50, col= "white", fill="#698adb") +
  geom_density(col = '#698adb') +
  theme_bw() + 
  labs(title = "Distribution of House Sale Prices in Ames, Iowa", x = 'Sale Price ($1000 USD)', y='Density') 


# most houses sold are ~ $160,000 
# data is a bit more right skewed - potentially log the price? 

median(house_price$SalePrice)  # median 159900
```

```{r  Sale Price Distribution}


house_price$SalePriceShort <- round(house_price$SalePrice/1000,2)
house_price$SalePriceShort

house_price %>% ggplot(aes(x = SalePriceShort)) + 
  geom_histogram(bins = 50, col= "white", fill="#698adb") +
  # geom_density(col = '#698adb') +
  theme_bw() + 
  theme_excel_new() + 
  labs(title = "Distribution of House Sale Prices in Ames, Iowa", x = 'Sale Price ($1000 USD)', y='Count') 


# most houses sold are ~ $160,000 
# data is a bit more right skewed - potentially log the price? 

median(house_price$SalePrice)  # median 159900
```







```{r  Logging Sale Price }
house_price <- data.frame(read.csv('data/Ames_HousePrice_cleaned.csv'))
house_price$LogSalePrice <- log(house_price$SalePrice)

house_price %>% ggplot(aes(x = LogSalePrice)) + 
  geom_histogram(aes(y=..density..), bins = 50, col= "white", fill="#698adb") +
  geom_density(col = '#698adb') +
  theme_bw() + 
  theme_excel_new() +
  labs(title = "Log Sale Price Distribution in Ames, Iowa", x = 'Log Sale Price', y='Density',) 
  
```




```{r  Where are the most expensive houses? Which neighborhoods?}
# geocoding addresses 

# full$Address <- str_c(full$MA_Line1,", ",full$MA_City)
# 
# full$Address <- str_c(full$address, ", ", full$MA_State)
# 
# full <- full %>% relocate(Address, .after =PID)
# 
# FullAddress <- full %>% 
#   select(PID, Address, GrLivArea, SalePrice.x)
# 
# write.csv(FullAddress, "Addresses.csv", row.names=FALSE)
```


```{r  Feature EDA: Lot Area }

house_price %>% 
  ggplot(aes(x = LotArea, y = SalePrice, color = SalePrice)) + 
  geom_point() +
  theme_ipsum() +
  labs(title = "Sale Price by Lot Area") 

# Some very large outliers (both sale price and lot area)
# lot area does not seem to be the most important factor in determining house price 

```

```{r   Examining LotArea outliers and Price outliers}

house_price %>% 
  arrange(desc(SalePrice))

house_price %>% 
  arrange(desc(LotArea))

```

```{r  Feature EDA: Price Per Sq Foot and Above Ground Living Area }
house_price <- house_price %>% 
  mutate(TotSF = TotalBsmtSF + GrLivArea) %>% 
  relocate(TotSF, .after = GrLivArea)

house_price <- house_price %>% 
  mutate(SFPrice = round(SalePrice/TotSF, 2)) %>% 
  relocate(SFPrice, .after = SalePrice)

house_price

house_price %>% 
  ggplot(aes(x=TotSF, y=SFPrice)) + 
  geom_smooth(method=lm, color = "#264D59") +
  geom_point(color="#43978D", alpha = 0.5) + 
  theme_ipsum() +
  labs(title = "Square Foot Price", x = "Total Living Area (Sq Ft)", y = "Price Per Sq")
```

```{r  Feature EDA: GrLivArea (above ground living area sq feet)}

class(house_price$GrLivArea)

house_price %>% 
  ggplot(aes(x=GrLivArea, y=SalePrice/1000, color = SalePriceShort)) + 
  geom_point(color="#8597f2", alpha = 0.5) +
  geom_smooth(method=lm, colour = "#627af0")+
  theme_bw()+
  theme_ipsum() +
  labs(title = "Price by Above Ground Living Area", x ="Above Ground Living Area (Sq Ft)", y='Sale Price ($1000 USD)')

# stronger correlation between living area sq foot and house price than lot area size 
# size does not look like it's that strong a factor in sq ft price

```

```{r  Feature EDA: OverallQual}
house_price$OverallQual <- factor(house_price$OverallQual)

house_price %>% 
  ggplot(aes(x= OverallQual, y=SFPrice, group=OverallQual)) + 
  geom_boxplot(color="#5a7fdb", fill="#ebae34", alpha=0.3) + 
  theme_ipsum() + 
  labs(title = "Quality by Sq Ft Price", x = "Overall Quality", y = "Price Per Sq Ft")

```

```{r  EDA: Neighbourhood and Quality}
options(repr.plot.width = 1, repr.plot.height = 2.5)
house_price %>% 
  mutate(Neigh = fct_reorder(Neighborhood, SalePrice)) %>% 
  mutate(SalePriceShort = round(SalePrice/1000),2) %>% 
  ggplot(aes(x = SalePriceShort, y = Neigh, fill = ..x..)) +
  geom_density_ridges_gradient(scale = 3, rel_min_height = 0.01) +
  scale_fill_viridis(name = "House Price") +
  labs(title = 'House Price Distribution by Neighborhood', x = 'Sale Price ($1000 USD)', y = 'Neighborhood') +
  theme_ipsum() +
    theme(
      legend.position="none",
      panel.spacing = unit(0.1, "lines"),
      strip.text.x = element_text(size = 8)
    )


```
```{r Distribution of Quality Rating by Neighborhood}

p1 <- house_price %>%
    ggplot(aes(x=Neighborhood, group=OverallQual, fill=OverallQual)) +
    geom_density(adjust=1.5, alpha=.4) +
    theme_ipsum() +
    coord_flip() +
    labs(title = 'Distribution of House Quality by Neighborhood')
p1

# I like the way this looks but it's probably not that informative 
```
```{r  Distr of House Qual by Neighborhood }

house_price %>% 
    group_by(Neighborhood) %>% 
    summarise(AvgQual = mean(as.integer(OverallQual))) %>% 
    mutate(Neigh = fct_reorder(Neighborhood, AvgQual)) %>% 
    ggplot(aes(x=Neigh, y=AvgQual, fill= Neigh)) +
    geom_col() + 
    labs(title = "Average Quality of Homes by Neighborhood", x="Neighborhood", y="Average Quality") +
    theme_bw() + 
    theme_ipsum() + 
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))  

  
```

```{r  Feature EDA: OverallCond}

class(house_price$OverallCond)

house_price$OverallCond <- factor(house_price$OverallCond)


house_price %>% 
  ggplot(aes(x= OverallCond, y=SFPrice)) + 
  geom_boxplot(color="#5a7fdb", fill="#ebae34", alpha=0.3) + 
  theme_ipsum() + 
  labs(title= "Overall Condition by Sq Ft Price", x ="Overall Condition", y="Sq Ft Price")

# Overall Condition of the house doesn't seem to dictate price as much as quality 
```

```{r   Feature Eng & EDA: House Age }

house_price <- house_price %>% 
  mutate(Age = YrSold - YearBuilt)

house_price <- house_price %>% relocate(Age, .after = YearBuilt)
house_price$SalePriceShort <- round(house_price$SalePrice/1000,2)

house_price %>% 
  ggplot(aes(x=Age, y=SalePriceShort, color=SalePriceShort)) + 
  geom_point() +
  theme_bw() + 
  theme_ipsum() +
  labs(title = 'House Age by Sale Price', x='Age', y='Sale Price (Thousand Dollars)' )

sum(is.na(house_price$Age))

house_price <- house_price %>%
  mutate(AgeBin = case_when(Age < 20 ~ '< 20', 
                            Age < 41 & Age >19 ~ '20-40',
                            Age < 61 & Age > 40 ~ '41-60',
                            Age < 81 & Age > 60 ~ '61-80', 
                            Age < 101 & Age > 80 ~ '81-100',
                            Age > 100 ~ '> 100'))

house_price$AgeBin <- factor(house_price$AgeBin)

house_price$AgeBin <- factor(house_price$AgeBin, levels=c('< 20', '20-40', '41-60', '61-80', '81-100', '> 100'))

levels(house_price$AgeBin)

house_price <- house_price %>% 
  relocate(AgeBin, .after = Age)

```

```{r  Feature EDA: Proportion Basement Finished }
library(grid)
# feature engineering 

house_price1 <- house_price

house_price1 <- house_price1 %>% 
  mutate(BsmtFinPerc = round((BsmtFinSF1 + BsmtFinSF2)*100/TotalBsmtSF), 2)

house_price1 <- house_price1 %>% relocate(BsmtFinPerc, .after = BsmtFinType1)

house_price1 <- house_price1[!house_price1$BsmtQual == "", ]

house_price1$BsmtQual <- factor(house_price1$BsmtQual)

levels(house_price$BsmtQual)
levels(house_price$BsmtQual) <- c("Excellent", "Good", "Avg", "Fair", "Poor")


options(repr.plot.width=20, repr.plot.height=6)

house_price1 %>% 
  ggplot(aes(x = BsmtFinPerc, y=SalePriceShort, color = BsmtQual, alpha =0.6)) +
  facet_grid( .~ AgeBin) +
  geom_point() + 
  labs(title = "Price by Percent Finished Basement Grouped by House Age", x = "Total % of Basement Finished", y="Sale Price ($1000 USD)", color = 'Basement \nQuality') +
  scale_color_manual(values=c("#138086", "#48bf91","#6ca0dc", "#D4CFC9","#EEB462")) +
  scale_alpha(guide = "none") + 
  theme_bw() +
  theme_ipsum() +
  theme(axis.text.x=element_text(size=6, angle=0, vjust=.8, hjust=0.8))




```



```{r  House Built Distributions (Grouped by Foundation)}
house_price2 <- read.csv("data/Ames_HousePrice_cleaned.csv")

house_price %>% 
  ggplot(aes(x=Age, y=SalePriceShort, colour = Foundation, alpha=0.3)) +
  geom_point() +
  theme_bw() + 
  theme_ipsum() + 
  scale_alpha(guide = "none") + 
  labs(title = 'House Age by Sale Price Grouped by Foundation', x = 'House Age', y='Sale Price ($1000 USD)') + 
  scale_color_manual(values=c("#CD7672", "#384E78","#534666", "#EEB462", "#D4CFC9", "#D45769"))

# It looks like houses built after 1980 are more desirable/sell higher 

```

```{r  House Built Distributions (Grouped by Foundation)}
house_price2 <- read.csv("data/Ames_HousePrice_cleaned.csv")

house_price %>% 
  ggplot(aes(x=Age, y=SalePriceShort, colour = MasVnrType, alpha=0.6)) +
  geom_point() +
  theme_bw() + 
  theme_ipsum() + 
  scale_alpha(guide = "none") + 
  labs(title = 'Year Built by Sale Price Grouped by Masonry Veneer Type', x = 'House Age', y='Sale Price')

# It looks like houses built after 1980 are more desirable/sell higher 

```

```{r  Exterior quality and mason veneer type} 


house_price %>% 
  ggplot(aes(x=Age, y=SalePriceShort, colour = Foundation, alpha=0.3)) +
  geom_point() +
  theme_bw() + 
  theme_ipsum() + 
  scale_alpha(guide = "none") + 
  labs(title = 'House Age by Sale Price Grouped by Foundation', x = 'House Age', y='Sale Price ($1000 USD)') + 
  scale_color_manual(values=c("#CD7672", "#384E78","#534666", "#EEB462", "#D4CFC9", "#D45769"))


```


```{r  Plots for Shiny Price Toggle Bar: Neighborhood price density vs Rest of Ames}

clean_dummy <- read.csv('data/cleaned_dummies.csv')

head(clean_dummy)


clean_dummy$nghbr_Blueste <- factor(clean_dummy$nghbr_Blueste)
clean_dummy %>% 
  mutate(SalePriceShort = round(SalePrice/1000,2)) %>% 
  ggplot(aes(x=SalePriceShort,  fill=nghbr_Blueste, group=nghbr_Blueste)) +
  geom_density(aes(y = ..scaled..), adjust=1.5, alpha=0.6) +
  scale_fill_viridis(discrete=TRUE) +
  scale_color_viridis(discrete=TRUE) +
  theme_ipsum() +
  labs(x='SalePrice ($1000 USD)', y='Density', title ='Price Distribution of Neighbourhood') +
  scale_fill_manual(values=c("#EEB462", "#CD7672"), name = "Legend", labels = c("All Other Neighborhoods", "Bluestem"))
  # scale_fill_discrete(labels = c("All Other Neighborhoods", "Bluestem")) + 
  # scale_fill_manual(values=c("#EEB462", "#CD7672")) 



```

```{r  House Age and Sq Ft Price }

house_price %>% 
  ggplot(aes(x=Age, y=SFPrice, color = as.integer(OverallQual), alpha = 0.9)) + 
  scale_color_gradient(low="#534666", high="#EEB462") +
  geom_point() + 
  geom_smooth(method=lm, color = '#534666') +
  scale_alpha(guide = "none") + 
  theme_bw() + 
  theme_ipsum() + 
  labs(x = 'House Age', y="Square Foot Price (USD)", title = "Square Foot Price by House Age", color='House Quality') 

```



```{r  Neighborhood Building Type }

hood_dummy = read.csv('data/hood_dummy.csv')

hood_dummy$BldgType <- factor(hood_dummy$BldgType)
hood_dummy$nghbr_Blueste <- factor(hood_dummy$nghbr_Blueste)

levels(hood_dummy$BldgType)
levels(hood_dummy$BldgType) <- c("1-Fam", "2-Fam Conversion", "Duplex", "Twnhs-Inside", "Twnhs-End")


df = hood_dummy %>% 
   group_by(nghbr_Blueste, BldgType) %>% 
   #filter(nghbr_Blueste == 1) %>% 
   summarise(MedianPrice = median(SalePrice/1000)) %>% 
   arrange(desc(MedianPrice)) 


bldg_levels = df %>% filter(nghbr_Blueste == 0) %>% .$BldgType

df %>% mutate(BldgType=factor(BldgType, bldg_levels)) %>%

# hood_dummy %>% 
#    group_by(nghbr_Blueste, BldgType) %>% 
#    #filter(nghbr_Blueste == 1) %>% 
#    summarise(MedianPrice = median(SalePrice/1000)) %>% 
#    arrange(desc(MedianPrice)) %>% 
   ggplot(aes(x=BldgType, y=MedianPrice, fill = nghbr_Blueste)) +
  geom_bar(position=position_dodge2(preserve = 'single'), stat='identity') + 
   theme_bw() + 
   theme_ipsum() +
   labs(x = 'Building Type', y='Median Sale Price ($1000 USD)', title = 'Price by House Building Type', color = 'Neighborhood') +
   scale_fill_manual(values=c("#264D59", "#138086","#43978D", "#63C0B5", "#90D1C9"), name = "Neighborhood", labels = c("All Other Neighborhoods", "Bluestem")) +
   theme(axis.text.x=element_text(size=11, angle=30, vjust=.8, hjust=0.8))
```

```{r}

hood_dummy$BedroomAbvGr <- factor(hood_dummy$BedroomAbvGr)

hood_dummy %>% 
   group_by(nghbr_Blueste, BedroomAbvGr) %>% 
   #filter(nghbr_Blueste == 1) %>% 
   summarise(MedBedPrice = median(SalePrice/1000)) %>% 
   arrange(desc(MedBedPrice)) %>% 
   ggplot(aes(x=BedroomAbvGr, y=(MedBedPrice), fill = nghbr_Blueste)) + 
   geom_bar(position=position_dodge2(preserve = 'single'), stat='identity') + 
   theme_bw() + 
   theme_ipsum() +
   labs(x = 'Bedrooms Above Ground', y='Median Sale Price ($1000 USD)', title = 'Price by Number of Bedrooms', color = 'Neighborhood') +
   scale_fill_manual(values=c("#CD7672", "#EEB462"), name = "Neighborhood", labels = c("All Other Neighborhoods", "Bluestem"))
```
```{r  Number of Bedrooms (All Ames) }

house_price$BedroomAbvGr <- factor(house_price$BedroomAbvGr)

class(house_price$BedroomAbvGr)

house_price %>% 
   group_by(BedroomAbvGr) %>% 
   summarise(medbedroomprice = median(SalePrice/1000)) %>% 
   arrange(desc(medbedroomprice)) %>%
   ggplot(aes(x=BedroomAbvGr, y=(medbedroomprice), fill = medbedroomprice)) +
   geom_bar(stat='identity', fill="#42a5c9") +
   theme_bw() +
   theme_ipsum() +
   labs(x = 'Bedrooms Above Ground', y='Median Sale Price ($1000 USD)', title = 'Price by Number of Bedrooms') +
  theme(legend.position="none")

```





```{r  Heating }

house_price$HeatingQC <- factor(house_price$HeatingQC)
levels(house_price$HeatingQC)
levels(house_price$HeatingQC) <- c("Excellent", "Fair", "Good", "Poor", "Avg")
house_price$HeatingQC <- factor(house_price$HeatingQC, levels = c("Excellent", "Good", "Avg", "Fair", "Poor"))


house_price %>% 
  group_by(HeatingQC) %>%
  summarise(medheating = median(SalePrice/1000)) %>% 
  arrange(desc(medheating)) %>% 
  ggplot(aes(x=HeatingQC, y=medheating)) +
  geom_col(fill = "#43978D") +
  theme_bw() +
  theme_ipsum() +
  labs(x = "Heating Quality", y="Median Price ($1000 USD)", title = "Price by Heating Quality")


```


```{r Kitchen Quality }

house_price$KitchenQual <- factor(house_price$KitchenQual)
class(house_price$KitchenQual)

levels(house_price$KitchenQual)
levels(house_price$KitchenQual) <- c("Excellent", "Fair", "Good", "Poor", "Avg")
house_price$KitchenQual <- factor(house_price$KitchenQual, levels = c("Excellent", "Good", "Avg", "Fair", "Poor"))


house_price %>% 
  ggplot(aes(x= KitchenQual, y=SalePrice/1000, group=KitchenQual)) + 
  geom_boxplot(color="#5a7fdb", fill="#ebae34", alpha=0.8) + 
  theme_ipsum() + 
  labs(title = "Price by Kitchen Quality", x = "Kitchen Quality", y = "Sale Price ($1000 USD)")

```
```{r  Baths }

house_price$FullBath <- factor(house_price$FullBath )
levels(house_price$FullBath )

house_price %>% 
  group_by(FullBath) %>%  
  mutate(bathmedprice = median(SalePrice/1000)) %>% 
  ggplot(aes(x=FullBath, y=bathmedprice/1000)) + 
  geom_col(fill = "#CD7672") + 
  labs(title = "Price by Full Baths", x="Number of Full Baths", y="Median Sale Price ($1000 USD)") + 
  theme_bw() + 
  theme_ipsum()

```
```{r  Fireplaces }

house_price3 <- house_price
house_price3 <- house_price[!house_price$FireplaceQu == "", ]

house_price3$Fireplaces <- factor(house_price3$Fireplaces)

house_price3$FireplaceQu <- factor(house_price3$FireplaceQu)

levels(house_price3$FireplaceQu)
levels(house_price3$FireplaceQu) <- c("Excellent", "Fair", "Good", "Poor", "Avg")
house_price3$FireplaceQu <- factor(house_price3$FireplaceQu, levels = c("Excellent", "Good", "Avg", "Fair", "Poor"))


house_price3 %>% 
  ggplot() + 
  geom_boxplot(aes(x= FireplaceQu, y=SalePrice/1000, fill = Fireplaces)) + 
  theme_ipsum() + 
  labs(title = "Price by Fireplace", x = "Fireplace Quality", y = "Sale Price ($1000 USD)") + 
  scale_fill_manual(values=c("#DC8865","#6AAB9C","#1ca9c9","#ffdb61"))
  

```







