---
title: "Ames EDA_MichelleBui"
author: "Michelle Bui"
date: "17/05/2022"
output: html_document
---

```{r  Loading Packages}
library(tidyverse)
library(ggridges)
library(viridis)
library(hrbrthemes)
library(ggmap)
library(ggExtra)
library(RColorBrewer)

getwd()
```



```{r loading files, merging datasets}
getwd()
house_price <- data.frame(read.csv('data/Ames_HousePrice_cleaned.csv'))
house_price

```

```{r  Full Model - which variables are initially significant?}
house_price
full_mod <- lm(SalePrice ~ ., data = house_price)
summary(full_mod)
```

```{r  Exploring NA values }
sum(is.na(house_price))  #615 NA values 
house_price[rowSums(is.na(house_price)) > 0, ]

```
```{r  What does the distribution of Sale Price look like?}

house_price$SalePriceShort <- round(house_price$SalePrice/1000,2)
house_price$SalePriceShort

house_price %>% ggplot(aes(x = SalePriceShort)) + 
  geom_histogram(bins = 50, col= "white", fill="#698adb") +
  theme_bw() + 
  theme_ipsum() + 
  labs(title = "Distribution of House Sale Prices in Ames, Iowa", x = 'Sale Price (Thousand Dollars)', y='Count',) 
  

# most houses sold are ~ $160,000 
# data is a bit more right skewed - potentially log the price? 

median(house_price$SalePrice)  # median 159900
```
```{r  Logging Sale Price }
house_price <- data.frame(read.csv('data/Ames_HousePrice_cleaned.csv'))
house_price$LogSalePrice <- log(house_price$SalePrice)

house_price %>% ggplot(aes(x = LogSalePrice)) + 
  geom_histogram(bins = 50, col= "white", fill="#698adb") +
  theme_bw() + 
  theme_ipsum() +
  labs(title = "Log Sale Price Distribution in Ames, Iowa", x = 'Log Sale Price', y='Count',) 
  
```




```{r  Where are the most expensive houses? Which neighborhoods?}
# geocoding addresses 

# full$Address <- str_c(full$MA_Line1,", ",full$MA_City)
# 
# full$Address <- str_c(full$address, ", ", full$MA_State)
# 
# full <- full %>% relocate(Address, .after =PID)
# 
# FullAddress <- full %>% 
#   select(PID, Address, GrLivArea, SalePrice.x)
# 
# write.csv(FullAddress, "Addresses.csv", row.names=FALSE)
```


```{r  Feature EDA: Lot Area }

house_price %>% 
  ggplot(aes(x = LotArea, y = SalePrice, color = SalePrice)) + 
  geom_point() +
  theme_ipsum() +
  labs(title = "Sale Price by Lot Area")

# Some very large outliers (both sale price and lot area)
# lot area does not seem to be the most important factor in determining house price 

```

```{r   Examining LotArea outliers and Price outliers}

house_price %>% 
  arrange(desc(SalePrice))

house_price %>% 
  arrange(desc(LotArea))

```

```{r  Feature EDA: GrLivArea (above ground living area sq feet)}

class(house_price$GrLivArea)

house_price %>% 
  ggplot(aes(x=GrLivArea, y=SFPrice, color = SFPrice)) + 
  geom_point() +
  theme_ipsum() +
  labs(title = "Above Ground Living Area by Sq Ft Price", x ="Above Ground Living Area (Sq Ft)", y='Sq Ft Price')

# stronger correlation between living area sq foot and house price than lot area size 
# size does not look like it's that strong a factor in sq ft price

```
```{r  Feature EDA: Price Per Sq Foot and Above Ground Living Area }
house_price <- house_price %>% 
  mutate(TotSF = TotalBsmtSF + GrLivArea) %>% 
  relocate(TotSF, .after = GrLivArea)

house_price <- house_price %>% 
  mutate(SFPrice = round(SalePrice/TotSF, 2)) %>% 
  relocate(SFPrice, .after = SalePrice)

house_price

house_price %>% 
  ggplot(aes(x=GrLivArea, y=SFPrice, color=SFPrice)) + 
  geom_point() + 
  theme_ipsum() +
  labs(title = "Square Foot Price by Above Ground Living Area", x = "Above Ground Living Area (Sq Ft)", y = "Price Per Sq")
```

```{r  Feature EDA: OverallQual}
house_price$OverallQual <- factor(house_price$OverallQual)

house_price %>% 
  ggplot(aes(x= OverallQual, y=SFPrice)) + 
  geom_boxplot(color="#5a7fdb", fill="#ebae34", alpha=0.3) + 
  theme_ipsum() + 
  labs(title = "Quality by Sq Ft Price", x = "Overall Quality", y = "Price Per Sq")

```

```{r  EDA: Neighbourhood and Quality}

house_price %>% 
  mutate(Neigh = fct_reorder(Neighborhood, SalePrice)) %>% 
  mutate(SalePriceShort = round(SalePrice/1000),2) %>% 
  ggplot(aes(x = SalePriceShort, y = Neigh, fill = ..x..)) +
  geom_density_ridges_gradient(scale = 3, rel_min_height = 0.01) +
  scale_fill_viridis(name = "House Price", option = "C") +
  labs(title = 'House Price Distribution by Neighborhood', x = 'Sale Price (Thousand Dollars)', y = 'Neighborhood') +
  theme_ipsum() +
    theme(
      legend.position="none",
      panel.spacing = unit(0.1, "lines"),
      strip.text.x = element_text(size = 8)
    )


```
```{r Distribution of Quality Rating by Neighborhood}

p1 <- house_price %>%
    ggplot(aes(x=Neighborhood, group=OverallQual, fill=OverallQual)) +
    geom_density(adjust=1.5, alpha=.4) +
    theme_ipsum() +
    coord_flip() +
    labs(title = 'Distribution of House Quality by Neighborhood')
p1

```
```{r  Distr of House Qual by Neighborhood }

house_price %>% 
    group_by(Neighborhood) %>% 
    summarise(AvgQual = mean(as.integer(OverallQual))) %>% 
    mutate(Neigh = fct_reorder(Neighborhood, AvgQual)) %>% 
    ggplot(aes(x=Neigh, y=AvgQual, fill= Neigh)) +
    geom_col() + 
    labs(title = "Average Quality of Homes by Neighborhood", x="Neighborhood", y="Average Quality") +
    theme_bw() + 
    theme_ipsum() + 
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))  

  
```

```{r  Feature EDA: OverallCond}

class(house_price$OverallCond)

house_price$OverallCond <- factor(house_price$OverallCond)


house_price %>% 
  ggplot(aes(x= OverallCond, y=SFPrice)) + 
  geom_boxplot(color="#5a7fdb", fill="#ebae34", alpha=0.3) + 
  theme_ipsum() + 
  labs(title= "Overall Condition by Sq Ft Price", x ="Overall Condition", y="Sq Ft Price")

# Overall Condition of the house doesn't seem to dictate price as much as quality 
```

```{r   Feature Eng & EDA: House Age }

house_price <- house_price %>% 
  mutate(Age = YrSold - YearBuilt)

house_price <- house_price %>% relocate(Age, .after = YearBuilt)

house_price %>% 
  ggplot(aes(x=Age, y=SalePrice, color=SalePrice)) + geom_point()

sum(is.na(house_price$Age))

house_price <- house_price %>%
  mutate(AgeBin = case_when(Age < 20 ~ 'Less Than 20', 
                            Age < 41 & Age >19 ~ '20-40',
                            Age < 61 & Age > 40 ~ '41-60',
                            Age < 81 & Age > 60 ~ '61-80', 
                            Age < 101 & Age > 80 ~ '81-100',
                            Age > 100 ~ 'Greater Than 100'))

house_price$AgeBin <- factor(house_price$AgeBin)

house_price$AgeBin <- factor(house_price$AgeBin, levels=c('Less Than 20', '20-40', '41-60', '61-80', '81-100', 'Greater Than 100'))

levels(house_price$AgeBin)

house_price <- house_price %>% 
  relocate(AgeBin, .after = Age)

```

```{r  Feature EDA: Proportion Basement Finished }

# feature engineering 
house_price <- house_price %>% 
  mutate(BsmtFinPerc = round((BsmtFinSF1 + BsmtFinSF2)*100/TotalBsmtSF), 2)

house_price <- house_price %>% relocate(BsmtFinPerc, .after = BsmtFinType1)

house_price

house_price %>% 
  ggplot(aes(x = BsmtFinPerc, y=SalePriceShort, color = SalePriceShort)) + 
  geom_point() + 
  facet_grid(~AgeBin) + 
  labs(title = "Price by Percent Finished Basement", x = "Total Percentage of Basement Finished", y="Sale Price (Thousand Dollars)")
```
```{r  To be continued... }

```

